### PR TITLE
Better capture device support

### PR DESCRIPTION
**Pull request by phlash**
Improving capture from IP cameras / phone apps, supporting multiple capture formats:

 * enables CV_CAP_PROP_CONVERT_RGB (actually BGR24, thanks OpenCV!), allowing many devices to work without us knowing exactly what they spit out and handling conversion.
 * background images now usable without colour space conversion (as default is BGR24 too).
 * resizes capture -> output, in case capture devices are weird (eg: mjpeg from my phone is two pixels off at 638x478??)
 * ~~captures in a separate thread to avoid video lag if TF isn't quick enough (it usually isn't!)~~

I've had a fun Saturday ;)

### CODE REVIEW

**Comment by floe** [comment]
Wow, that's a big one :-) Do you think you can split it, one PR for the threading stuff and one for the color conversion?

**Comment by phlash** [comment]
Yep, no problem, I'll take out the threading stuff for this PR..

**Comment by cob16** [comment]
:+1: This pr has got `Logitech HD Pro Webcam C920` working for me :smile:

**Comment by floe** [comment]
Sorry for the long silence, I haven't forgotten about this, I'm just absolutely swamped ATM :-/

**Review by BenBE — COMMENTED** [review]
LGTM. Needs some rebasing for current master and to work together with my PR #36. Would make the mirroring feature from my PR even much saner (avoiding two colorspace conversions that YUYV requires me for horizontal mirroring …

**Comment by floe** [comment]
The main reason why I've been reluctant to merge this one is because it adds a noticeable amount of overhead, at least on my machine, due to the multiple colorspace conversions. OTOH, when using the Google Meet network, there's a bit more headroom as it is way more efficient...

**Comment by phlash** [comment]
Superseded by #48

**Pull request closed without merging**
